id: IA08537FE
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-22T22:51:24+00:00'
last_modified: '2022-06-08T06:02:55.915784+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1KG21954
  title: དཔལ་ཀྱེ་རྡོ་རྗེའི་རྣམ་པར་བཤད་པ་ལེགས་བཤད་ཉི་མའི་འོད་ཟེར།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    4E4E:
      image_group_id: I1KG21971
      title: ''
      total_pages: 356
      order: 1
      base_file: 4E4E.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
